-- DIRECT INSERT: Students table
-- Generated from real-students-import-csv.csv
-- Splits Full Name into first_name (first word) and last_name (remainder)
-- program_id and cohort_id are intentionally left NULL
-- Run in Supabase SQL Editor

INSERT INTO students (first_name, last_name, username, email, role, account_status, is_active,
  points, exercises_completed, workshops_attended, standup_attended, mentoring_attended, points_assigned)
VALUES
  ('Abduljalil', 'Mohamed Wael Najjar', 'najjar_a', 'abduljalil.najjar@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Abdullah', 'Mutlaq', 'mutlaq_a', 'abdullah.mutlaq@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Abdulrahman', 'Amein', 'amein_a', 'abdulrahman.amein@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Adonijah', 'Manyange', 'manyage_a', 'adonijah.manyange@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Adrian', 'Sardinata', 'sardinat_a', 'adrian.sardinata@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Ahmad', 'Zaid Wakili', 'zaid-wak_a', 'ahmad.zaid@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Alessandro', 'Poggio', 'poggio_a', 'alessandro.poggio@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Alexey', 'Markov', 'markov_a', 'alexey.markov@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Alisa', 'Kalinina', 'kalinina_a', 'alisa.kalnina@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Alona', 'Khudoliei', 'khudolie_a', 'alona.khudoliei@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Andrei', 'Vilnoiu', 'vilnoiu_a', 'andrei.vilnoiu@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Andres', 'Pepi Lascano', 'pepi-las_a', 'andres.lascano@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Angelo', 'Andreas', 'andreas_a', 'angelo.andreas@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Anna', 'Kashkina', 'kashkina_a', 'anna.kashkina@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Annalize', 'Ross', 'ross_an', 'annalize.ross@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Anthony', 'Daskalis', 'daskalis_a', 'anthony.daskalis@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Apostolos', 'Vetsos', 'vetsos_a', 'apostolos.vetsos@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Aras', 'Masiulis', NULL, 'aras@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Arkaprabha', 'Sinharoy', 'sinharoy_a', 'arkaprabha.sinharoy@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Arnoldas', 'Bimbiras', 'bimbiras_a', 'arnoldas.bimbiras@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Artem', 'Monchuk', 'monchuk_a', 'artem.monchuk@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Arturas', 'Jacevicius', 'jacevici_a', 'arturas.jacevicius@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Arvydas', 'Gimbutis', 'gimbutis_a', 'arvydas.gimbutis@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('August', 'Brunnberg Frigo', 'brunnber_a', 'august.frigo@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Augustas', 'Medonis', 'medonis_a', 'augustas.medonis@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Aurimas', 'Čepulis', 'cepulis_a', 'aurimas.cepulis@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Bartosz', 'Zielinski', 'zielinsk_b', 'bartosz.zielinski@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Bassey', 'Ita', 'ita_b', 'bassey.ita@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Berk', 'Can Dagdelen', 'dagdelen_b', 'berk.dagdelen@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Billy', 'Van Niekerk', 'van-niek_b', 'billy.vanniekerk@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Binazel', 'Monteiro', 'monteiro_b', 'binazel.monteiro@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Bi-Swirri', 'Pearl Forba', 'forba_b', 'biswirri.forba@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Carlo', 'Moretti', 'moretti_c', 'carlo.moretti@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Charl', 'Van Zyl', 'van-zyl_c', 'charl.van@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Cheryl', 'Kautzman', 'kautzman_c', 'cheryl.kautzman@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Chigbo', 'Oguoba', 'oguoba_c', 'chigbo.oguoba@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Christine', 'Plenge', 'plenge_c', 'christine.plenge@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Constantin', 'Tofan', 'tofan_c', 'constantin.tofan@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Courtney', 'Popp', 'popp_c', 'courtney.popp@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Daniel', 'Araujo Caccia Gouveia', 'araujo-c_d', 'daniel.araujo@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Daniel', 'Nechtan', 'nechtan_d', 'daniel.nechtan@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Dave', 'Corley', 'corley_d', 'dave.corley@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Dennis', 'Mwendwa', 'mwendwa_d', 'dennis.mwendwa@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Diogo', 'Oliveira', 'oliveira_d', 'diogo.oliveira@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Domantas', 'Urbonavičius', 'urbonavi_d', 'domantas.urbonavicius@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Domas', 'Vysockis', 'vysockis_d', 'domas.vysockis@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Dovile', 'Miskinyte', 'miskinyt_d', 'dovile.miskinyte@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Dovydas', 'Montvillas', 'montvill_d', 'dovydas.montvillas@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Dumitru', 'Constantin Vladut', 'constant_d', 'dumitru.vladut@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Dylan', 'Cahill', 'cahill_d', 'dylan.cahill@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Ecaterina', 'Malac', 'malac_e', 'ecaterina.malac@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Ece', 'Sezgin', 'sezgin_e', 'ece.sezgin@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Edria', 'Coomber', 'coomber_e', 'edria.coomber@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Emilis', 'Butrimas', 'butrimas_e', 'emilis.butrimas@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Epoldina', 'Varela Landim', 'landim_e', 'epoldina.landim@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Eraers', 'Olivier', 'olivier_e', 'eraers.olivier@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('George', 'Etaiseh Esomba', 'etaiseh_e', 'esomba.etaiseh@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Evelina', 'Rose-Anne Tickaite', 'tickaite_e', 'evelina.tickaite@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Eylul', 'Bozkurt', 'bozkurt_e', 'eylul.bozkurt@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Felipe', 'Martinez Moreno', 'martine_fe', 'felipe.martinez@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Felipe', 'Elias Rito Morales', 'elias-ri_f', 'felipe.morales@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Filippos', 'Andreas Mavraganis', 'andreas-_f', 'filippos.mavraganis@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Firat', 'Demir', 'demir_f', 'firat.demir@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Francisco', 'Jose Sanabria Quintero', 'jose-san_f', 'francisco.jose@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Gabriel', 'Medeiros', 'medeiros_g', 'gabriel.medeiros@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Gabriela', 'Suarez', 'suarez_g', 'gabriela.suarez@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Giovani', 'Di Pietro', 'dipietro_g', 'giovanni.dipietro@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Goncalo', 'Lagoa', 'lagoa_g', 'goncalo.lagoa@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Grace', 'Oga', 'oga_gr', 'grace.oga@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Guido', 'Morales', 'morales_g', 'guido.morales@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Gustavo', 'Viola Costa', 'costa_g', 'gustavo.costa@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Hala', 'Kaheel', 'kaheel_h', 'hala.kaheel@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Hami', 'Ibriyamov', 'ibriyamo_h', 'hami.ibriyamov@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Hanna', 'Danylova', 'danylova_h', 'hanna.danylova@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Hans', 'Martens', 'martens_h', 'hans.martens@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Hashim', 'Kader', 'kader_h', 'hashim.kader@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Hassan', 'Emad', 'emad_h', 'hassan.emad@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Hatice', 'Elezi', 'elezi_h', 'hatice.elezi@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Hazem', 'Barman', 'barman_h', 'hazem.barman@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Helen', 'Malatanti', 'malatant_h', 'helen.malatanti@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Hugo', 'Hopp', 'hopp_h', 'hugo.hopp@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Huseyin', 'Bugra Nalci', 'bugra-na_h', 'huseyin.bugra@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Ibrahim', 'Anan', 'anan_i', 'ibrahim.anan@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Ieva', 'Patackait', 'patackai_i', 'ieva.patackait@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Igor', 'Castro de Gissi', 'castro-d_i', 'igor.castro@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Ilias', 'Markelis', 'markelis_i', 'ilias.markelis@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Illia', 'Kovalenko', 'kovalenk_i', 'illia.kovalenko@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Inga', 'Hilbolling Nienstedt', 'hilbolli_i', 'inga.hilbolling@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Iryna', 'Mormul', 'mormul_i', 'iryna.mormul@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Isaac', 'Shittu', 'shittu_i', 'isaac.shittu@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Issac', 'Chang', 'chang_i', 'issac.chang@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Yuri', 'Bartalo', 'bartalo_y', 'ivan.yuri@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Ivanashe', 'OGrady Usiri', 'ogrady-u_i', 'ivanashe.usiri@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Jani', 'Burnazi', 'burnazi_j', 'jani.burnazi@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Jaunius', 'Zulonas', 'zulonas_j', 'jaunius.zulonas@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Jean', 'Bosco Bizimungu', 'bizimung_j', 'jean.bizimungu@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Jenny', 'Paola Rivieccio', 'paola-ri_j', 'jenny.rivieccio@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Joanna', 'Niazi', 'niazi_j', 'joanna.niazi@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Joanna', 'Stefanowska', 'stefanow_j', 'joanna.stefanowska@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Johannes', 'Marinus Wubs', 'wubs_j', 'johannes.wubs@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Jonathan', 'El Khoury', 'el-khour_j', 'jonathan.elkhoury@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Jonathan', 'Mungufeni', 'mungufen_j', 'jonathan.mungufeni@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Juan', 'Ramon Garcia', 'ramon-ga_j', 'juan.garcia@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Julia', 'Miasko', 'miasko_j', 'julia.miasko@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Justas', 'Glodenis', 'glodenis_j', 'justas.glodenis@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Justina', 'Pavilovskyte', 'pavilovs_j', 'justina.pavilovskyte@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Kaloyan', 'Kostadinov', 'kostadin_k', 'kaloyan.kostadinov@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Katja', 'Dow', 'dow_k', 'katja.dow@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Keenon', 'Ribberink', 'ribberin_k', 'keenon.ribberink@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Kim', 'Chi Hoang', 'hoang_k', 'kim.hoang@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Kipras', 'Karalevičius', 'karalevi_k', 'kipras.karalevicius@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Kirils', 'Jegorovs', 'jegorovs_k', 'kirils.jegorovs@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Kristina', 'Pociute', 'pociute_k', 'kristina.pociute@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Laeticia', 'Blanc', 'blanc_la', 'laeticia.blanc@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Larissa', 'Almeida', 'almeida_l', 'larissa.almeida@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Lena', 'Alsleiman', 'alsleima_l', 'lena.alsleiman@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Lizzy', 'Obonyo', 'obonyo_l', 'lizzy.obonyo@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Lucy', 'Sears', 'sears_l', 'lucy.sears@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Lukas', 'Banevicius', 'banevici_l', 'lukas.banevicius@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Lukas', 'Sadecky', 'sadecky_l', 'lukas.sadecky@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Mahmood', 'Abdullah', 'abdulla_ma', 'mahmood.abdullah@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Mahmoud', 'Salem', 'salem_m', 'mahmoud.salem@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Malik', 'Petion', 'petion_m', 'malik.petion@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Maria', 'Eduarda Tavares Vieira', 'tavares-_m', 'maria.eduarda@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('María', 'Van den Brink', 'van-den-_m', 'maria.van@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Mariam', 'Turkishvili', 'turkishv_m', 'mariam.turkishvili@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Mariangela', 'Palacios', 'palacios_m', 'mariangela.palacios@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Marianne', 'Rezzonico', 'rezzonic_m', 'marianne.rezzonico@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Marie', 'Toussaint Chedeline', 'chedelin_m', 'marie.chedeline@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Marvin', 'Kirsch', 'kirsch_m', 'marvin.kirsch@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Mathias', 'Bezandry', 'bezandry_m', 'mathias.bezandry@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Mathias', 'Sletterhage', 'sletterh_m', 'mathias.sletterhage@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Max', 'La Faille', 'lafaille_m', 'max.lafaille@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Mehdi', 'Daoud', 'daoud_me', 'mehdi.daoud@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Merher', 'Morzy', 'morzy_m', 'merher.morzy@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Migle', 'Matiukaite', 'matiukai_m', 'migle.matiukaite@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Milda', 'Zvirblyte', 'zvirblyt_m', 'milda.zvirblyte@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Milla', 'Plomp Plomp', 'plomp_m', 'milla.plomp@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Muhammad', 'Jibril', 'jibril_m', 'muhammad.jibril@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Muhammad', 'Mahmud Haris', 'mahmud-h_m', 'muhammad.mahmud@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Naijeria', 'Toweett', 'toweett_n', 'naijeria.toweett@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Naiza', 'Dusoruth', 'dusoruth_n', 'naiza.dusoruth@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Natalie', 'Peyre', 'peyre_n', 'natalie.peyre@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Natallia', 'Tsviatkova', 'tsviatko_n', 'natallia.tsviatkova@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Neilas', 'Sunklodas', 'sunkloda_n', 'neilas.sunklodas@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Neline', 'Theron', 'theron_n', 'neline.theron@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Niklas', 'Larsen-Disney', 'larsen-d_n', 'niklas.larsen-disney@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Nikolay', 'Kirilov', 'kirilov_n', 'nikolay.kirilov@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Nojus', 'Jasevicius', 'jasevici_n', 'nojus.jasevicius@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Nojus', 'Saulys', 'saulys_n', 'nojus.saulys@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Nozwelo', 'Moyo', 'moyo_n', 'nozwelo.moyo@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Nura', 'Adem', 'adem_n', 'nura.adem@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Nympha', 'Pamba', 'pamba_n', 'nympha.pamba@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Oliver', 'Antoni', 'antoni_o', 'oliver.antoni@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Osagie', 'Alonge', 'alonge_o', 'osagie.alonge@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Pablo', 'Samuel Barrientos Wolfs', 'barrient_p', 'pablol.barrientos@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Panagiotis', 'Pattes', 'pattes_p', 'panagiotis.pattes@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Patrikas', 'Šimkus', 'simkus_p', 'patrikas.simkus@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Patryk', 'Sieradzki', 'sieradzk_p', 'patryk.sieradzki@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Pijus', 'Bilinskas', 'bilinska_p', 'pijus.bilinskas@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Pravish', 'Narrainen', 'narraine_p', 'pravish.narrainen@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Rajab', 'Mailov', 'mailov_r', 'rajab-mailov@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Ralfs', 'Lorencs', 'lorencs_r', 'ralfs.lorencs@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Rami', 'Alkinani', 'alkinan_ra', 'rami.alkani@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Aras', 'Ramus', 'ramus_ar', 'ramusis@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Rebecca', 'Casaroto Gomes', 'casaroto_r', 'rebecca.gomes@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Rebecca', 'Douglas Gonzalez', 'douglas-_r', 'rebecca.gonzalez@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Rhys', 'Christopher', 'christop_r', 'rhys.christopher@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Rimgaudas', 'Jurkaitis', 'jurkaiti_r', 'rimgaudas.jurkaitis@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Rohan', 'Morgan', 'morgan_r', 'rohan.morgan@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Rose', 'Lavelle', 'lavelle_r', 'rose.lavelle@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Sahan', 'Caliskan', 'caliskan_s', 'sahan.caliskan@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Said', 'Anan', 'anan_s', 'said.anan@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Sam', 'Butler', 'butler_s', 'sam.butler@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Sam', 'Moustafa', 'moustafa_s', 'sam.moustafa@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Samia', 'Slimani', 'slimani_s', 'samia.slimani@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Samuel', 'Davies', 'davies_s', 'samuel.davies@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Samuel', 'Ilenloa', 'ilenloa_s', 'samuel.ilenloa@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Sandra', 'Wong', 'wong_s', 'sandra.wong@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Sarp', 'Pehlivan', 'pehlivan_s', 'sarp.pehlivan@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Dennis', 'Schmidt', 'schmidt_d', 'schmidt.dennis@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Scott', 'Chang', 'chang_s', 'scott.chang@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Shaker', 'Musa', 'musa_s', 'shaker.musa@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Shaun', 'Bennie', 'bennie_s', 'shaun.bennie@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Sigidas', 'Peciukaitis', 'peciukai_s', 'sigidas.peciukaitis@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Stefanos', 'Migkas', 'migkas_s', 'stefanos.migkas@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Susanna', 'Pezzini', 'pezzini_s', 'susanna.pezzini@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Tadas', 'Milvydas', 'milvydas_t', 'tadas.milvydas@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Talal', 'Almatrafi', 'almatra_t', 'talal.almatrafi@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Tamta', 'Lomidze', 'lomidze_t', 'tamta.lomidze@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Tania', 'Moreira', 'moreira_t', 'tania.moreira@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Tautvydas', 'Bačiulis', 'baciulis_t', 'tautvydas.baciulis@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Taylor', 'Durtschi', 'durtschi_t', 'taylor.durtschi@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Tim', 'Cvetko', 'cvetko_t', 'tim.cvetko@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Tino', 'Rajkovic', 'rajkovic_t', 'tino.rajkovic@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Tjaž', 'Gabrovšek', 'gabrovse_t', 'tjaz.gabrovsek@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Todor', 'Simeonov', 'simeonov_t', 'todor.simeonov@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Tomas', 'Tokoly', 'tokoly_t', 'tomas.tokoly@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Ugnius', 'Virmauskas', 'virmausk_u', 'ugnius.virmauskas@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Viktor', 'Parvanov', 'parvanov_v', 'viktor.parvanov@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Viktor', 'Pavliuk', 'pavliuk_v', 'viktor.pavliuk@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Viktoriia', 'Didarova', 'didarova_v', 'viktoriia.didarova@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Vladislav', 'Doynov', 'doynov_v', 'vladislav.doynov@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Volodymyr', 'Muzyka', 'muzyka_v', 'volodymyr.muzyka@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Vytautas', 'Pavilonis', 'paviloni_v', 'vytautas.pavilonis@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Wilberforce', 'Musombi', 'musombi_w', 'wilberforce.musombi@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Wilhelm', 'Johan Geldenhuys', 'geldenhu_w', 'wilhelm.geldenhuys@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('William', 'Steinke de Mello', 'steinked_w', 'william.mello@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Wilson', 'Omonzokpia', 'omonzokp_w', 'wilson.omonzokpia@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Wopke', 'Rietveld', 'rietveld_w', 'wopke.rietveld@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Yaroslav', 'Pakhaliuk', 'pakhaliu_y', 'yaroslav.pakhaliuk@elu.nl', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Yelyzaveta', 'Samodid', 'samodid_y', 'yelyzaveta.samodid@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Yevheniia', 'Pashko', 'pashko_y', 'yevheniia.pashko@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Zahra', 'Seyedeh Zaki', 'zaki-_z', 'zahra.seyedeh@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Žilvinas', 'Gruodis', 'gruodis_z', 'zilvinas.gruodis@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0),
  ('Žygimantas', 'Poderis', 'poderis_z', 'zygimantas.poderis@amsterdam.tech', 'student', 'Active', true, 0, 0, 0, 0, 0, 0)
ON CONFLICT (email) DO NOTHING;

-- Verify: count inserted students
SELECT COUNT(*) AS total_students FROM students;

-- Verify: check for any missing usernames (scraper cannot process these)
SELECT first_name, last_name, email FROM students WHERE username IS NULL OR username = '' ORDER BY last_name;